#!/usr/bin/env python

from __future__ import absolute_import, division, print_function

from nav_msgs.msg import Odometry, Path
import rospy


# TODO (peckama2) in the future, this could be replaced by cras_topic_tools change_header


rospy.init_node("visualize_odom", anonymous=True)

pub = rospy.Publisher("odom_vis", Odometry, queue_size=10)
fixed_frame = rospy.get_param("~fixed_frame")


def cb(msg):
    # by overwriting the frame to fixed frame, we disable any transformations in rviz and display the odometry as is
    msg.header.frame_id = fixed_frame
    pub.publish(msg)


sub = rospy.Subscriber("odom", Odometry, cb, queue_size=10)

rospy.spin()
